### ISSUE TITLE
Tiktok says connection error

### ISSUE THREAD

**Issue by fuad00** [sumous/TikTok-SSL-Pinning-Bypass#1]
I'm getting "connection error".
Iphone 6s IOS 14.4 checkra1n

**Comment by fuad00** [comment]
I'm trying to see API requests via proxying using "Burp Suite" but no luck

**Comment by sumous** [comment]
which version of your tiktok?

**Comment by fuad00** [comment]
> which version of your tiktok?

It's lasted version (22.8.0 at the moment) 
I just want to sniff live stream gifts (They are in the newest versions only)

**Comment by sumous** [comment]
I have no time to view this version, you can downgrade to 20.6.

**Comment by novitae** [comment]
> I have no time to view this version, you can downgrade to 20.6.

If one day you start working again on this project, on `23.8.0` it works for most of the requests but for :
```
https://webcast16-normal-c-useast1a.tiktokv.com
https://p16-sign-va.tiktokcdn.com
https://mon.tiktokv.com
https://api16-core-c-useast1a.tiktokv.com
https://api19-normal-c-useast1a.tiktokv.com
https://log19-normal-useast1a.tiktokv.com
```
Other requests are working well

**Comment by sumous** [comment]
I tested on `23.8.0`  just now, It works.

**Comment by sumous** [comment]
@novitae What is your bundle id of Tiktok?

**Comment by novitae** [comment]
> @novitae What is your bundle id of Tiktok?

The bundle id is `com.zhiliaoapp.musically`, however during some tests on other repos before, I tried to install some other versions of Tiktok via Altstore, and Altstore told me that Tiktok has 8 app ids. So if the original version has really 8 app ids, it might come from it ... idk

I'm available for any tests.

Also here what Im seing (every grey points are SSL handshake fails):
<img width="915" alt="Capture d’écran 2022-04-01 à 15 15 14" src="https://user-images.githubusercontent.com/85891169/161270866-712fa7e5-69a5-4ad4-98e4-9f9dfc48e374.png">

**Comment by novitae** [comment]
The main place where I get a lot of ssl handshake errors is at the login page, password recovery, register etc ... Check if it works for you there so you can clearly know if im just a noob or if its comes from the package

**Comment by sumous** [comment]
The register is OK. You can see the picture below:
![1648819408076](https://user-images.githubusercontent.com/1303581/161272325-f3d3bf2e-ee2c-481b-a89e-eb06e744f995.jpg)

**Comment by novitae** [comment]
well it's pretty weird it works now ... but there is still all these requests that cannot be read. I think these are some requests sending infos about all my activity on the app, because they get blocked because the ssl fails with it and nothing changes n the app, so its not that important.

Thanks for you help !
